meta_product_name: "Super Barman"
meta_title: "Super Barman  - Hire a bartender for your party for only 50â‚¬."
meta_description: "Bring the bar to you and serve the best ever cocktails thanks to our curated bartenders. Your parties will never be the same again."
meta_image: "banner.png"                       # should exist in `app/assets/images/`
